name: Main Pipeline
on: 
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo test
        run: cargo test --verbose --color always